---
title: Michaelblog
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- Gemfile
- Gemfile.lock
baseurl: ''
future: true
gems:
- jekyll-paginate
- kramdown
- rouge
excerpt_separator: "<!–break–>"
paginate: 5
paginate_path: read/page:num
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
